spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          low-case-service-id: true

server:
  port: ${SERVER_PORT:8080}

cloud:
  discovery:
    enabled: true
    eureka:
      client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
          defaultZone: http://localhost:8761/eureka
