spring:
  application:
    name: mscloudgateway
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          low-case-service-id: true

server:
  port: ${SERVER_PORT:8080}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
    # ip-address:
    # instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
